### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by yanlinghuah** [kazuhiro1999/Automatic-Evaluation-of-Dance-Movements#1]
Thanks for your great work! I have one question regarding the datasets. Is this the complete data you used to train the encoder and evaluation model? Also, I noticed there is an advice database with detailed text feedback. Do you plan on releasing this part as well?

**Comment by kazuhiro1999** [comment]
Thank you for your message.

Regarding the datasets, we have only released a portion of the data for which we obtained open-source permissions. It is because some of the data contains personal information.

We do have the text feedback data as well, but this is not publicly released either.

If you need access to the dataset, I will confirm with my supervisor. If possible, please send me an email with details of the intended use, and I will consider it as part of my discussion.

Best regards,

**Comment by yanlinghuah** [comment]
> Thank you for your message.
> 
> Regarding the datasets, we have only released a portion of the data for which we obtained open-source permissions. It is because some of the data contains personal information.
> 
> We do have the text feedback data as well, but this is not publicly released either.
> 
> If you need access to the dataset, I will confirm with my supervisor. If possible, please send me an email with details of the intended use, and I will consider it as part of my discussion.
> 
> Best regards,

Thank you for the information. If possible, I would like to request access to the full dataset, including the text feedback data. I am a student at Lund University, majoring in VR/AR, and I plan to use the data solely for my school project, strictly for academic purposes, not commercial use. You can reach me at ya4736hu-s@student.lu.se.

**Comment by kazuhiro1999** [comment]
I understand your request. However, I will need a little time (probably 2 to 3 days) as some adjustments and preparations are required before sharing the data. I will get back to you with further information.

If you don't mind, could you please provide more details about the specific use of the dataset? I am curious about how the data will be utilized in your project.

**Comment by kazuhiro1999** [comment]
@yanlinghuah 
The dataset is now ready.
You can download it from [Google Drive](https://drive.google.com/file/d/1iyCYbBtQt5RQzc8xBSe8hx0R7gJ7aClk/view?usp=sharing).
I look forward to your positive update.

**Comment by yanlinghuah** [comment]
> @yanlinghuah The dataset is now ready. You can download it from [Google Drive](https://drive.google.com/file/d/1iyCYbBtQt5RQzc8xBSe8hx0R7gJ7aClk/view?usp=sharing). I look forward to your positive update.

Apologies for the delayed response! I’m currently on a short trip and will be back next week. Regarding the datasets, I plan to use them to develop a VR dance coach app, along with implementing an evaluation method from your paper. I really appreciate your assistance and will review it once I return.

**Comment by kazuhiro1999** [comment]
I'm going to close this issue for now, but please feel free to reach out if there are any concerns. I'm also very interested in the future development of automated dance evaluation research, so please keep in touch!

**Comment by yanlinghuah** [comment]
> I'm going to close this issue for now, but please feel free to reach out if there are any concerns. I'm also very interested in the future development of automated dance evaluation research, so please keep in touch!

Thank you for your assistance and for providing the data. I’ve successfully downloaded it. I’m wondering if it would be possible to release the complete dataset, or alternatively, send it to my personal email for academic purposes. I will ensure that the dataset is properly cited in any work I publish. Thanks again for your help!

**Comment by kazuhiro1999** [comment]
We’re unable to release the full dataset due to privacy concerns. Some participants, as indicated in their consent forms, opted not to share their data publicly, and we must respect their wishes.

However, we do have a subset of motion data (without video) that some participants have consented to share under restricted access. If you are interested in accessing this subset, please let me know, and we can arrange it accordingly.

**Comment by yanlinghuah** [comment]
> We’re unable to release the full dataset due to privacy concerns. Some participants, as indicated in their consent forms, opted not to share their data publicly, and we must respect their wishes.
> 
> However, we do have a subset of motion data (without video) that some participants have consented to share under restricted access. If you are interested in accessing this subset, please let me know, and we can arrange it accordingly.

Yes, sure. I really appreciate your help.

**Comment by kazuhiro1999** [comment]
After reviewing the data access permissions, I realized that aside from two participants whose data is restricted for internal lab use only, the remaining motion data has already been made publicly available. Unfortunately, this means there isn’t any additional data we can share beyond what is already accessible.

I apologize for any confusion.

**Comment by yanlinghuah** [comment]
> After reviewing the data access permissions, I realized that aside from two participants whose data is restricted for internal lab use only, the remaining motion data has already been made publicly available. Unfortunately, this means there isn’t any additional data we can share beyond what is already accessible.
> 
> I apologize for any confusion.

It's totally fine. I understand this situation. By the way, is it possible to release the weight of encoder and evaluation model? I will only use for my course project, and will properly cite this in my course report. Thanks again !!!

**Comment by kazuhiro1999** [comment]
Of course. Which format would you prefer for the model, such as Keras (.h5) or ONNX (.onnx)?

**Comment by yanlinghuah** [comment]
> Of course. Which format would you prefer for the model, such as Keras (.h5) or ONNX (.onnx)?

Maybe both. Thanks for this !!!

**Comment by yanlinghuah** [comment]
> Of course. Which format would you prefer for the model, such as Keras (.h5) or ONNX (.onnx)?

Hi, sorry to bother you again. Is there any update on the model's weight?

**Comment by kazuhiro1999** [comment]
The model's weights will be made available within this week.

As for the inference program, including the preprocessing steps, I’m currently in the process of organizing everything. However, due to some other pressing matters, it may take a bit longer. I appreciate your understanding and patience in the meantime.

**Comment by yanlinghuah** [comment]
> The model's weights will be made available within this week.
> 
> As for the inference program, including the preprocessing steps, I’m currently in the process of organizing everything. However, due to some other pressing matters, it may take a bit longer. I appreciate your understanding and patience in the meantime.

Thanks for the update! Looking forward to the weights and appreciate your efforts on the inference program—take your time!

**Comment by yanlinghuah** [comment]
> The model's weights will be made available within this week.
> 
> As for the inference program, including the preprocessing steps, I’m currently in the process of organizing everything. However, due to some other pressing matters, it may take a bit longer. I appreciate your understanding and patience in the meantime.

Hi, any update?

**Comment by kazuhiro1999** [comment]
I wanted to apologize for the delay in making the inference program available. Thank you for your patience and understanding.

I'm pleased to let you know that:
- The pre-trained model is now available for download under [Releases/v1.0](https://github.com/kazuhiro1999/Automatic-Evaluation-of-Dance-Movements/releases/tag/v1.0).
- The inference program can be run directly on Colab. You can access it here: [inference.ipynb](https://github.com/kazuhiro1999/Automatic-Evaluation-of-Dance-Movements/blob/main/inference.ipynb).  

If you encounter any issues or have questions while using the program, please don't hesitate to reach out.

**Comment by yanlinghuah** [comment]
> I wanted to apologize for the delay in making the inference program available. Thank you for your patience and understanding.
> 
> I'm pleased to let you know that:
> 
> * The pre-trained model is now available for download under [Releases/v1.0](https://github.com/kazuhiro1999/Automatic-Evaluation-of-Dance-Movements/releases/tag/v1.0).
> * The inference program can be run directly on Colab. You can access it here: [inference.ipynb](https://github.com/kazuhiro1999/Automatic-Evaluation-of-Dance-Movements/blob/main/inference.ipynb).
> 
> If you encounter any issues or have questions while using the program, please don't hesitate to reach out.

Glad to hear that !! I'll have a try !
